---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  type: NodePort
  selector:
    app: sonarr
  ports:
    - name: http
      port: 8989
      protocol: TCP
      targetPort: 8989  
  externalIPs:
    - 192.168.0.211
    - 192.168.0.221
    - 192.168.0.222 
    - 192.168.0.223
