---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: synology-sonarr-media
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: synology
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: synology.home
    path: "/volume1/video/TV"
