---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-sonarr
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 5Gi

